@startuml
|开发 dev|
start
:feature\n基于Master创建需求分支;
:feature\n开发功能，研发自测;
:feature\n联调测试;
|#AntiqueWhite|测试 test|
:合并开发代码至测试分支;
:release\n第一轮测试;
|开发 dev|
:feature\nBug修复;
|#AntiqueWhite|测试 test|
:合并开发代码至测试分支;
:release\n第二轮测试;
:release\n测试报告;
|生产 prod|
:release\n发布生产镜像，上线;
:验证通过，合并release代码至master;
stop
@enduml
