
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public      # 必须与user-service一致
        group: DEFAULT_GROUP   # 必须与user-service一致
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    sentinel:
      transport:
        dashboard: localhost:8080
    loadbalancer:
      configurations: health-check
      cache:
        enabled: true
        caffeine:
          spec: maximumSize=500, expireAfterWrite=5s
