server:
  port: 80

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: ${spring.application.name}
      config:
        server-addr: localhost:8848
        file-extension: yml
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/order/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG