server:
  port: 8081

spring:
  application:
    name: user-service
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
        watch-delay: 5000  # 延迟注册时间（单位：毫秒）
        group: DEFAULT_GROUP
        file-extension: yaml
        refresh-enabled: true
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        heartbeat-interval: 5000  # 每5秒发送一次心跳
  config:
    import: optional:nacos:${spring.application.name}.yaml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
  type-handlers-package: com.redjujubetree.common.mybatis.typehandler

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: TRACE
    reactor.netty.http.client: DEBUG
