server:
  port: 8081

logging:
  config: classpath:logback-spring.xml

#spring:
#  jackson:
#    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
#  datasource:
#    url: jdbc:sqlite:/Users/kenny/IdeaProjects/userDb # 创建的sqlite数据库所在路径
#    username: # 因为没有用户名和密码，所以这两个参数就没有值
#    password:
#    driver-class-name: org.sqlite.JDBC # sqlite驱动

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
  type-handlers-package: com.redjujubetree.common.mybatis.typehandler