server:
  port: 8081

spring:
  application:
    name: ztb-service
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
  datasource:
    url: jdbc:mysql://47.113.144.60:7500/ztbgl_batch5?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1234Qwer
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
  # type-handlers-package: com.redjujubetree.common.mybatis.typehandler