@startuml
title 标书复用确认
|客户端|
start
:点击标书复用;
if (此操作将覆盖掉本分标同目录的文件内容，请确认是否导入?) is (否)
    :不复用;
    stop
endif
if (分标正在制作中) is (否)
:生成word;
note
    注意需要修改文件内容的部分
endnote
:标书状态修改为制作中;
:资质信息复用;

'关联项拷贝复用文件的对应资质信息（拷贝数据库中存储的资质信息），如果资质信息字段的文本格式不一致时（下拉框时需要判断下拉的内容是否一致），则不导入资质信息
:word文件复用;
endif
end
@enduml
