@startuml
title 复用标书手动关联流程图
start
:右键选择简要关联的目录;
note right
仅末级节点有关联选项
仅展示服用标书的同父级目录的子目录选项
endnote
:选择关联目录;
note
   1. 初次关联，同时关联父级目录
   2. 关联其他子节点，只能关联同一父级目录下的子节点
   3. 更改父级目录，需要删除父级节点下所有的已关联的节点
endnote
if (类型是否一致) is  (否) then
    :提示 字段类型不一致无法关联;
    note
    类型： 文本 文本域 数字 日期 时间 下拉
    endnote
    stop;
endif
:关联直接父级节点关联关系;

@enduml
