@startuml
skinparam linetype ortho

class ztb_reuse_catalog_rel  <<分标复用>>{
    id bigint 主键
    vid_bid_id 分标目录ID
    reuse_vid_bid_id 复用分标ID
    version 版本号
    udpate_by 更新人
    del_flag 删除标识
}

class ztb_reuse_catalog_rel_item <<复用目录关联关系>> {
    id 主键
    reuse_catalog_rel_id 复用关联关系ID
    leaves_id 目录ID
    leaves_name 节点名称
    rel_leaves_id 复用目录ID
    rel_leaves_name 复用节点名称
    del_flag 删除标识
}

ztb_reuse_catalog_rel_item o--> ztb_reuse_catalog_rel : reuse_catalog_rel_id -> id

@enduml