@startuml
'https://plantuml.com/activity-diagram-beta
'选择投标文件上传日志中，当前登录账号名称与上传日志中供应商名称一致的数据（项目-分标-虚拟分标一致），再选择当前电脑中存储的项目。
title 获取用户可复用的分标信息
|客户端|
start
:FE Request;
|招投标管理|
:根据登录信息查找供应商可以服用的分标信息;
|客户端|
:获取供应商可以服用的分标的信息;
|本地服务|
:查找本地服务中可以复用的分标信息;
note right
    携带查询得到的数据，
endnote
:取本地服务数据与远程服务数据的交集;
|客户端|
:获取供应商可以服用的分标的信息;
|客户端|
:初始化客服用分标信息列表;
:客户选择复用分标;
|本地服务|
:复用分标的结构化目录;
|客户端|
:待复用分标信息;
end
@enduml